'use client';
import {useEffect,useState} from 'react';
import {Search,Sparkles,ArrowUpRight,Database,Layers3,BookOpen,Swords,Users,ArrowRight,Link2,LoaderCircle,Hexagon,SlidersHorizontal} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {type Entry} from '@/lib/game-data';
export default function Page(){
 const [game,setGame]=useState('all'),[category,setCategory]=useState('all'),[q,setQ]=useState(''),[submitted,setSubmitted]=useState(''),[entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[connected,setConnected]=useState(false),[ai,setAi]=useState(false),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[detail,setDetail]=useState<Entry|null>(null),[settings,setSettings]=useState(false);
 async function search(query=q,g=game,c=category,useAi=false){setLoading(true);setError('');setAnswer('');setSubmitted(query);try{const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q:query,game:g,category:c,ai:useAi})});const d=await r.json();if(!r.ok)throw Error(d.error);setEntries(d.entries);setConnected(d.connected);setAi(d.ai);setAnswer(d.answer);setError(d.warning||'');}catch(e){setError((e as Error).message);setEntries([]);}finally{setLoading(false);}}
 useEffect(()=>{search('');},[]);
 const icon=(c:string)=>c==='ไอเทม'?<Swords/>:c==='ตัวละคร'?<Users/>:<BookOpen/>;
 return <div className="shell"><header><a className="brand" href="/"><span className="brand-symbol"><Hexagon size={25}/></span>NEXUS<span className="brand-sub">GAME DATA CENTER</span></a><button className="connection" onClick={()=>setSettings(true)}><Database size={16}/>{connected?'เชื่อมต่อ Supabase แล้ว':'โหมดตัวอย่าง'}<ArrowUpRight size={15}/></button></header>
 <main><div className="eyebrow"><span/> YOUR GAME KNOWLEDGE, CONNECTED</div><div className="heading"><div><h1>ทุกข้อมูลเกม<br/><span>ค้นเจอได้ในที่เดียว</span></h1><p>สำรวจ TOSM และ Zone4 หรือให้ AI ช่วยหาคำตอบจากคลังข้อมูล</p></div><div className="index-label">THE KNOWLEDGE HUB <span>01 — 02</span></div></div>
 <section className="search-box"><form onSubmit={e=>{e.preventDefault();search(q,game,category,true)}}><Search className="search-icon"/><input aria-label="ค้นหาข้อมูลเกม" placeholder="ค้นหาไอเทม ตัวละคร หรือพิมพ์คำถามของคุณ…" maxLength={500} value={q} onChange={e=>setQ(e.target.value)}/><button disabled={loading} className="ai-button" type="submit">{loading?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>}ค้นหาด้วย AI <ArrowRight size={17}/></button></form><div className="search-bottom"><span><Sparkles size={14}/>{connected&&ai?'AI พร้อมช่วยค้นหาจากฐานข้อมูล':'AI จะพร้อมใช้งานหลังเชื่อมต่อข้อมูลและบริการ'}</span><button disabled={loading} onClick={()=>search()}>ค้นหาด้วยคำสำคัญ <ArrowUpRight size={14}/></button></div></section>
 <div className="suggestions"><span>ลองค้นหา</span>{['มือใหม่','อุปกรณ์','สกิล'].map(t=><button disabled={loading} key={t} onClick={()=>{setQ(t);search(t,game,category,true)}}>{t}<ArrowUpRight size={13}/></button>)}</div>
 <section className="game-grid" aria-label="เลือกเกม">{[{id:'TOSM',label:'TOSM',sub:'คลังข้อมูล TOSM',n:'01',cls:'tosm'},{id:'Zone4',label:'ZONE4',sub:'คลังข้อมูล Zone4',n:'02',cls:'zone'}].map(g=><button disabled={loading} key={g.id} className={`game-card ${g.cls} ${game===g.id?'selected':''}`} onClick={()=>{const v=game===g.id?'all':g.id;setGame(v);search(q,v)}}><div className="game-card-top"><span>GAME DATABASE</span><span>{g.n}</span></div><div className="game-title">{g.label}<ArrowUpRight/></div><div className="game-card-bottom"><span>{g.sub}</span><span>{game===g.id?'กำลังเลือก':'สำรวจข้อมูล'} <ArrowRight size={15}/></span></div></button>)}</section>
 <section className="library"><div className="section-title"><h2><Layers3 size={21}/>คลังข้อมูล{game!=='all'&&<span className="game-pill">{game}</span>}</h2><span>{connected?'SUPABASE DATABASE':'DEMO COLLECTION'}</span></div><div className="filters"><Tabs value={category} onValueChange={c=>{setCategory(c);search(q,game,c)}}><TabsList>{[['all','ทั้งหมด'],['ไอเทม','ไอเทม'],['ตัวละคร','ตัวละคร / อาชีพ'],['คู่มือ','คู่มือ']].map(([v,l])=><TabsTrigger disabled={loading} key={v} value={v}>{l}</TabsTrigger>)}</TabsList></Tabs><button disabled={loading} className="clear" onClick={()=>{setQ('');setGame('all');setCategory('all');search('','all','all')}}><SlidersHorizontal size={15}/>ล้างตัวกรอง</button></div>
 {!connected&&<p className="demo-note">ข้อมูลตัวอย่างสำหรับทดลองระบบ • ยังไม่ใช่ข้อมูลเกมจริง</p>}
 {error&&<div role="alert" className="error">{error}<button disabled={loading} onClick={()=>search()}>ลองใหม่</button></div>}
 {answer&&<div className="answer" aria-live="polite"><h3><Sparkles size={18}/>{connected&&ai?'คำตอบจาก AI':connected?'ผลการค้นหา':'ผลการค้นหาตัวอย่าง'}</h3><p>{answer}</p>{connected&&ai&&entries.slice(0,6).map((x,i)=><button key={x.id} onClick={()=>setDetail(x)}>[{i+1}] {x.title}</button>)}</div>}
 <div className="result-caption"><span>{submitted?`ผลการค้นหา “${submitted}”`:'สำรวจข้อมูลทั้งหมด'}</span><span aria-live="polite">{loading?'กำลังค้นหา…':`${entries.length} รายการ${connected&&entries.length===60?' (สูงสุด 60 รายการ)':''}`}</span></div>
 <div className="results">{loading?[1,2,3].map(x=><Skeleton key={x} className="h-52 rounded-xl"/>):entries.map(x=><button key={x.id} className="entry" onClick={()=>setDetail(x)}><div className="entry-top"><span className={`entry-icon ${x.game==='Zone4'?'orange':''}`}>{icon(x.category)}</span><span className="entry-game">{x.game}</span><ArrowUpRight size={17}/></div><span className="category">{x.category}</span><h3>{x.title}</h3><p>{x.summary}</p><div className="tags">{x.tags.map(t=><span key={t}>{t}</span>)}</div></button>)}</div>
 {!loading&&!entries.length&&!error&&<div className="empty"><Search size={28}/><h3>{connected&&!submitted&&game==='all'&&category==='all'?'คลังข้อมูลพร้อมรับข้อมูลเกมแล้ว':'ไม่พบข้อมูลที่ตรงกับคำค้น'}</h3><p>{connected&&!submitted&&game==='all'&&category==='all'?'ยังไม่มีรายการที่เผยแพร่ เพิ่มข้อมูล TOSM หรือ Zone4 ใน Supabase เพื่อเริ่มค้นหา':'ลองใช้คำที่สั้นลง หรือเลือกหมวดทั้งหมด'}</p></div>}
 </section><footer><span className="footer-brand">NEXUS / GAME DATA CENTER</span><span>TOSM & ZONE4 <span className="footer-dot">·</span> ค้นหาจากข้อมูลที่มีแหล่งอ้างอิง</span></footer></main>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="detail-modal">{detail&&<><DialogTitle>{detail.title}</DialogTitle><DialogDescription>{detail.game} / {detail.category}{!connected?' · ข้อมูลตัวอย่าง':''}</DialogDescription><p className="detail-text">{detail.content}</p>{detail.source_file&&<p className="muted">แหล่งข้อมูล: {detail.source_file}<br/>รหัส {detail.source_id} · แถว {detail.source_row} · {detail.source_category}</p>}<div className="tags">{detail.tags.map(t=><span key={t}>{t}</span>)}</div>{detail.source_url&&/^https?:\/\//i.test(detail.source_url)?<a className="source" href={detail.source_url} target="_blank" rel="noopener noreferrer"><Link2 size={16}/>เปิดแหล่งข้อมูล</a>:<p className="muted">{detail.source_file?'อ้างอิงจากไฟล์ FAQ ที่นำเข้า':'ยังไม่ได้ระบุลิงก์แหล่งข้อมูล'}</p>}</>}</DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent><DialogTitle>สถานะการเชื่อมต่อ</DialogTitle><DialogDescription>การตั้งค่าสำหรับเจ้าของศูนย์ข้อมูล</DialogDescription><div className="setup-row"><Database size={20}/>Supabase <strong>{connected?'เชื่อมต่อแล้ว':'รอเชื่อมต่อ'}</strong></div><div className="setup-row"><Sparkles size={20}/>AI <strong>{ai?'ตั้งค่าแล้ว':'รอตั้งค่า'}</strong></div><p>เชื่อมต่อโปรเจกต์ Supabase และตารางข้อมูลเกมของคุณเพื่อแทนที่ข้อมูลตัวอย่าง จากนั้นเชื่อมต่อบริการ AI เพื่อค้นหาด้วยคำถามและสรุปคำตอบพร้อมแหล่งอ้างอิง</p><p className="muted">แจ้ง URL โปรเจกต์และโครงสร้างตารางให้ผู้ดูแลตั้งค่าการเชื่อมต่อบนเซิร์ฟเวอร์</p></DialogContent></Dialog></div>
}
