'use client';
import {useEffect,useRef,useState} from 'react';
import DeletePanel from '@/components/delete-panel';
import {gameStyle} from '@/lib/game-colors';
import SearchBox from '@/components/search-box';
import AccessGate,{AccountControls,useAccess} from '@/components/access-gate';
import {protectedFetch} from '@/lib/client';
import {Search,Plus,ArrowUpRight,ArrowRight,BookOpen,Layers3,Gamepad2,Settings2,ChevronLeft,ChevronRight,Copy,Check,X,RefreshCw,LayoutGrid,List,SlidersHorizontal,Sparkles,LoaderCircle,Command,FileText} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Skeleton} from '@/components/ui/skeleton';
import ManagePanel,{type Game} from '@/components/manage-panel';
import {type Entry} from '@/lib/game-data';
type Catalog={games:Game[];topics:{game:string;topic:string;count:number}[];total:number;connected:boolean;ai:boolean;adminReady:boolean};
type Filter={q:string;game:string;category:string;page:number;pageSize:number;sort:string;ai:boolean;terms?:string[]};
const initial:Filter={q:'',game:'all',category:'all',page:1,pageSize:24,sort:'relevance',ai:false};
const topicNames:Record<string,string>={'Account':'บัญชีผู้เล่น','Gameplay':'การเล่นเกม','Game and Launcher':'เกมและ Launcher','Game & Launcher':'เกมและ Launcher','Technical Support':'ปัญหาทางเทคนิค','Community &report':'ชุมชนและแจ้งปัญหา','Payment':'การเติมเงิน','Event & News':'กิจกรรมและข่าวสาร'};
const label=(t:string)=>topicNames[t]||t;
function AnswerText({text}:{text:string}){return <>{text.replace(/\\n/g,'\n').split(/(https?:\/\/[^\s<>"\u0E00-\u0E7F]+)/g).map((s,i)=>/^https?:\/\//.test(s)?<a key={i} href={s} target="_blank" rel="noopener noreferrer">{s}</a>:s)}</>;}
export default function Page(){return <AccessGate><Workspace/></AccessGate>;}
function Workspace(){
 const {member}=useAccess();const canEdit=member.role!=='viewer';
 const [catalog,setCatalog]=useState<Catalog|null>(null),[catalogError,setCatalogError]=useState(''),[f,setF]=useState<Filter>(initial),[draft,setDraft]=useState(''),[rows,setRows]=useState<Entry[]>([]),[total,setTotal]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(''),[detail,setDetail]=useState<Entry|null>(null),[manage,setManage]=useState(false),[view,setView]=useState('list'),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(''),[answer,setAnswer]=useState(''),[sources,setSources]=useState<Entry[]>([]),[retry,setRetry]=useState(0);
 const [deleteEntry,setDeleteEntry]=useState<Entry|null>(null),[notice,setNotice]=useState('');
 const [editingEntry,setEditingEntry]=useState<Entry|null>(null);
 const searchTerms=useRef<string[]|undefined>(undefined);
 const request=useRef(0),searchRef=useRef<HTMLInputElement>(null);
 async function loadCatalog(){try{setCatalogError('');const r=await protectedFetch('/api/catalog',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setCatalog(d);}catch(e){setCatalogError((e as Error).message);}}
 useEffect(()=>{loadCatalog();const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 useEffect(()=>{const n=++request.current;const controller=new AbortController();setBusy(true);setError('');setAnswer('');setSources([]);(async()=>{try{const r=await protectedFetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f),signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'ค้นหาไม่สำเร็จ');if(n!==request.current)return;const pages=Math.max(1,Math.ceil(d.total/f.pageSize));if(f.page>pages){setF(v=>({...v,page:pages,ai:false}));return;}setRows(d.entries);setTotal(d.total);setAnswer(d.answer||'');setSources(d.sources||[]);if(d.warning)setError(d.warning);if(d.terms)searchTerms.current=d.terms;}catch(e){if(controller.signal.aborted)return;if(n===request.current){setRows([]);setTotal(0);setError((e as Error).message);}}finally{if(n===request.current)setBusy(false);}})();return()=>controller.abort();},[f,retry]);
 const games=catalog?.games||[],selected=games.find(g=>g.id===f.game),pages=Math.max(1,Math.ceil(total/f.pageSize));
 const topics=[...new Set((catalog?.topics||[]).filter(t=>f.game==='all'||t.game===f.game).map(t=>t.topic))];
 function change(p:Partial<Filter>){searchTerms.current=undefined;setF(v=>({...v,...p,page:1,ai:false,terms:undefined}));}
 function reset(){setDraft('');setF(initial);}
 function open(e:Entry){setDetail(e);setCopied(false);setCopyError('');}
 async function copy(){if(!detail)return;try{await navigator.clipboard.writeText(detail.title+'\n\n'+detail.content);setCopied(true);setCopyError('');}catch{setCopyError('คัดลอกอัตโนมัติไม่ได้ กรุณาเลือกข้อความแล้วคัดลอก');}}
 const range=total?`${(f.page-1)*f.pageSize+1}–${Math.min(f.page*f.pageSize,total)}`:'0';
 return <div className="workspace"><aside className="sidebar"><a href="/" className="brand"><span className="brand-mark"><Layers3 size={23}/></span><span>NEXUS<small>GAME KNOWLEDGE</small></span></a><div className="side-label">WORKSPACE</div><button className={'side-item '+(f.game==='all'?'active':'')} onClick={()=>change({game:'all',category:'all'})}><BookOpen size={18}/>คลังความรู้ทั้งหมด<span>{catalog?.total??'—'}</span></button><div className="side-section"><span>เกมของคุณ</span><button hidden={!canEdit} aria-label="เพิ่มเกมใหม่" onClick={()=>setManage(true)}><Plus size={18}/></button></div><nav className="game-nav" aria-label="เลือกเกม">{games.map(g=><button key={g.id} style={gameStyle(g,games)} className={'side-item game-side-item '+(g.id===f.game?'active':'')} onClick={()=>change({game:g.id,category:'all'})}><span className={'game-initial '+g.color}>{g.image_path?<img src={'/api/game-image?game='+encodeURIComponent(g.id)+'&v='+encodeURIComponent(g.image_path)} alt=""/>:g.name.slice(0,2).toUpperCase()}</span><span className="game-name">{g.name}</span><span>{g.count}</span></button>)}</nav><button hidden={!canEdit} className="add-game" onClick={()=>setManage(true)}><Plus size={17}/>เพิ่มเกมใหม่</button><div className="sidebar-bottom"><div className="side-help"><Gamepad2 size={22}/><p>เกมใหม่ ความรู้ใหม่<small>ขยายคลังข้อมูลได้ทุกเมื่อ</small></p></div><button hidden={!canEdit} className="side-item" onClick={()=>setManage(true)}><Settings2 size={18}/>จัดการคลังข้อมูล</button><span className="side-version">NEXUS / VERSION 1.5</span></div></aside>
 <div className={'main-wrap '+(selected?'game-workspace':'')} style={selected?gameStyle(selected,games):undefined}><header className="topbar"><div className="breadcrumb"><BookOpen size={17}/><span>คลังความรู้</span><span>/</span><strong>{selected?.name||'ทุกเกม'}</strong></div><button hidden={!canEdit} className="ghost" onClick={()=>setManage(true)}><Settings2 size={17}/><span>จัดการ</span></button><AccountControls/></header><main><div className="page-heading"><div>{selected?.image_path&&<img className="game-cover" src={'/api/game-image?game='+encodeURIComponent(selected.id)+'&v='+encodeURIComponent(selected.image_path)} alt={selected.name}/> }<div className="eyebrow">YOUR KNOWLEDGE, ORGANIZED</div><h1>{selected?.name||'คลังความรู้เกม'}<span className="title-dot">.</span></h1><p>{selected?.description||'ค้นคำตอบที่ต้องการ แล้วกลับไปสนุกกับเกมต่อ'}</p></div><button hidden={!canEdit} className="primary" onClick={()=>setManage(true)}><Plus size={17}/>เพิ่มเกม / หัวข้อ</button></div>
 <div className="mobile-games"><select aria-label="เลือกเกม" value={f.game} onChange={e=>change({game:e.target.value,category:'all'})}><option value="all">ทุกเกม ({catalog?.total??0})</option>{games.map(g=><option key={g.id} value={g.id}>{g.name} ({g.count})</option>)}</select></div>
 <section className="search-area"><SearchBox value={draft} game={f.game} category={f.category} games={games} inputRef={searchRef} onChange={setDraft} onSubmit={q=>change({q})} onOpen={open}/><div className="search-meta"><span>รองรับคำไทย–อังกฤษ คำบางส่วน และหัวข้อใกล้เคียงใน{selected?'เกมนี้':'คลังข้อมูล'}</span>{catalog?.ai&&<button disabled={!draft.trim()||busy} onClick={()=>setF(v=>({...v,q:draft.trim(),page:1,ai:true,terms:undefined}))}><Sparkles size={14}/>ให้ AI ช่วยสรุป</button>}<span className="data-state">{catalog?catalog.connected?'ข้อมูลจากฐานข้อมูล':'โหมดตัวอย่าง':'กำลังเชื่อมต่อ…'}</span></div></section>
 <div className="collection-heading"><h2><Layers3 size={19}/>{f.q?'ผลการค้นหา':'สำรวจคลังข้อมูล'}<span className="number-badge">{busy?'…':total.toLocaleString()}</span></h2><div className="view-toggle" aria-label="รูปแบบการแสดงผล"><button className={view==='list'?'chosen':''} aria-pressed={view==='list'} aria-label="แสดงรายการ" onClick={()=>setView('list')}><List size={17}/></button><button className={view==='grid'?'chosen':''} aria-pressed={view==='grid'} aria-label="แสดงการ์ด" onClick={()=>setView('grid')}><LayoutGrid size={17}/></button></div></div>
 <div className="toolbar"><div className="filters"><SlidersHorizontal size={16}/><select aria-label="หมวดหมู่" value={f.category} onChange={e=>change({category:e.target.value})}><option value="all">ทุกหมวดหมู่</option>{topics.map(t=><option key={t} value={t}>{label(t)}{t==='Game & Launcher'?' (หมวดเดิม)':''}</option>)}</select><select aria-label="เรียงลำดับ" value={f.sort} onChange={e=>change({sort:e.target.value})}><option value="relevance">เกี่ยวข้องมากที่สุด</option><option value="newest">อัปเดตล่าสุด</option><option value="title">เรียงตามชื่อ</option></select></div><label className="per-page">แสดง<select value={f.pageSize} onChange={e=>change({pageSize:Number(e.target.value)})} aria-label="จำนวนต่อหน้า"><option value={24}>24</option><option value={48}>48</option><option value={96}>96</option></select>ต่อหน้า</label></div>
 {(f.q||f.category!=='all'||f.game!=='all')&&<div className="active-filters">{f.q&&<span>“{f.q}”<button aria-label="ล้างคำค้น" onClick={()=>{setDraft('');change({q:''});}}><X size={13}/></button></span>}{selected&&<span>{selected.name}</span>}{f.category!=='all'&&<span>{label(f.category)}</span>}<button onClick={reset}>ล้างตัวกรองทั้งหมด</button></div>}
 {notice&&<p role="status" className="success">{notice}</p>}{(catalogError||error)&&<div className="error" role="alert"><span>{catalogError||error}</span><button onClick={()=>{loadCatalog();setRetry(n=>n+1);}}><RefreshCw size={15}/>ลองอีกครั้ง</button></div>}
 {answer&&<section className="ai-answer"><h3><Sparkles size={18}/>คำตอบจาก AI</h3><p>{answer}</p><div>{sources.map((s,i)=><button key={s.id} onClick={()=>open(s)}>[{i+1}] {s.title}</button>)}</div></section>}
 <div aria-live="polite" className="result-info"><span>{busy?'กำลังค้นหาข้อมูล…':`แสดง ${range} จาก ${total.toLocaleString()} หัวข้อ`}</span><span>{busy?'':`หน้า ${f.page} / ${pages}`}</span></div>
 {busy?<div className="loading-list">{[1,2,3,4].map(n=><Skeleton key={n} className="h-24 rounded-xl"/>)}</div>:rows.length?<div className={'results '+view}>{rows.map(e=>{const g=games.find(g=>g.id===e.game);return <button key={e.id} className="knowledge-card game-card" style={g?gameStyle(g,games):undefined} onClick={()=>open(e)}><span className={'entry-symbol '+(g?.color||'teal')}><FileText size={21}/></span><div className="entry-body"><div className="entry-meta"><span>{g?.name||e.game}</span><span className="meta-dot">/</span><span>{label(e.topic||e.source_category||e.category)}</span></div><h3>{e.title}</h3>{e.match_kind==='related'&&<span className="related-badge">หัวข้อใกล้เคียง</span>}<p>{e.summary}</p></div><div className="entry-trail"><span>{e.source_id||'บทความ'}</span><ArrowUpRight size={18}/></div></button>})}</div>:!error&&<div className="empty"><div><Search size={27}/></div><h3>{f.q?'ไม่พบหัวข้อที่ตรงกับคำค้น':'ยังไม่มีหัวข้อในหมวดนี้'}</h3><p>{f.q?'ลองคำที่สั้นลง เช่น ชื่อระบบ หรือรหัส FAQ':'เพิ่มหัวข้อแรก หรือเลือกเกมและหมวดหมู่อื่น'}</p><button className="secondary" onClick={reset}>ดูข้อมูลทั้งหมด</button></div>}
 <nav className="pagination" aria-label="เปลี่ยนหน้าผลลัพธ์"><button disabled={busy||f.page<=1} onClick={()=>setF(v=>({...v,page:v.page-1,ai:false,terms:searchTerms.current}))}><ChevronLeft size={17}/>ก่อนหน้า</button><div>{Array.from(new Set([1,...Array.from({length:5},(_,i)=>f.page-2+i).filter(n=>n>=1&&n<=pages),pages])).sort((a,b)=>a-b).map((n,i,a)=><span key={n}>{i>0&&n-a[i-1]>1&&<span className="ellipsis">…</span>}<button disabled={busy} className={n===f.page?'current':''} aria-current={n===f.page?'page':undefined} onClick={()=>setF(v=>({...v,page:n,ai:false,terms:searchTerms.current}))}>{n}</button></span>)}</div><button disabled={busy||f.page>=pages} onClick={()=>setF(v=>({...v,page:v.page+1,ai:false,terms:searchTerms.current}))}>ถัดไป<ChevronRight size={17}/></button></nav>
 <footer><span>NEXUS <span>/</span> GAME KNOWLEDGE</span><span>VERSION 1.5 · พื้นที่สำหรับสมาชิก</span></footer></main></div>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="detail-modal">{detail&&<><div className="detail-tag"><BookOpen size={15}/>{games.find(g=>g.id===detail.game)?.name||detail.game} · {label(detail.topic||detail.source_category||detail.category)}</div><DialogTitle className="detail-title">{detail.title}</DialogTitle><DialogDescription>{detail.source_id||'บทความในคลังความรู้'}</DialogDescription><div className="detail-answer"><AnswerText text={detail.content}/></div><div className="source-box"><FileText size={18}/><div><strong>แหล่งอ้างอิง</strong><p>{detail.source_file?`${detail.source_file} · แถว ${detail.source_row}`:'เพิ่มโดยผู้ดูแลคลังข้อมูล'}</p>{detail.source_url&&/^https?:\/\//.test(detail.source_url)&&<a href={detail.source_url} target="_blank" rel="noopener noreferrer">เปิดแหล่งข้อมูล<ArrowUpRight size={14}/></a>}</div></div>{canEdit&&<button className="danger" onClick={()=>{setDeleteEntry(detail);setDetail(null);}}>ลบหัวข้อนี้</button>}{canEdit&&<button className="secondary" onClick={()=>{setEditingEntry(detail);setDetail(null);setManage(true);}}>แก้ไขหัวข้อนี้</button>}<button className="secondary copy-button" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'คัดลอกแล้ว':'คัดลอกคำตอบ'}</button>{copyError&&<p role="alert">{copyError}</p>}</>}</DialogContent></Dialog>
 <Dialog open={!!deleteEntry&&canEdit} onOpenChange={v=>{if(!v)setDeleteEntry(null);}}><DialogContent className="manage-modal"><DialogTitle>ลบหัวข้อ</DialogTitle><DialogDescription>ตรวจชื่อและยืนยันก่อนลบข้อมูล</DialogDescription>{deleteEntry&&<DeletePanel target={{kind:'entry',entry:deleteEntry}} onCancel={()=>setDeleteEntry(null)} onDeleted={(game,warning)=>{setDeleteEntry(null);setNotice(warning||'ลบหัวข้อแล้ว');loadCatalog();setDraft('');change({q:'',game,category:'all'});setRetry(n=>n+1);}}/>}</DialogContent></Dialog>
 <Dialog open={manage&&canEdit} onOpenChange={v=>{setManage(v);if(!v)setEditingEntry(null);}}><DialogContent className="manage-modal"><DialogTitle>จัดการคลังข้อมูล</DialogTitle><DialogDescription>เพิ่มเกม แก้ไขชื่อ และเผยแพร่หัวข้อใหม่</DialogDescription><ManagePanel games={games} topics={catalog?.topics||[]} entry={editingEntry} onEntryDone={()=>setEditingEntry(null)} onSaved={id=>{loadCatalog();change({game:id,category:'all',q:''});setDraft('');setRetry(n=>n+1);}}/></DialogContent></Dialog>
 </div>;
}
