'use client';
import {createContext,useContext,useEffect,useState,useCallback,useRef} from 'react';
import {Layers3,ShieldCheck,Clock3,LogOut,Sun,Moon,RefreshCw,LoaderCircle} from 'lucide-react';
import type {Member} from '@/lib/auth';
const Context=createContext<{member:Member;refresh:()=>void}|null>(null);
export const useAccess=()=>{const value=useContext(Context);if(!value)throw Error('Access context missing');return value;};
export function ThemeToggle(){const [dark,setDark]=useState(false);useEffect(()=>{setDark(document.documentElement.dataset.theme==='dark');},[]);return <button className="ghost theme-toggle" aria-label={dark?'เปลี่ยนเป็นโหมดสว่าง':'เปลี่ยนเป็นโหมดมืด'} title={dark?'Light mode':'Dark mode'} onClick={()=>{const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('nexus-theme',next?'dark':'light');}catch{}}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>;}
export function AccountControls(){const {member}=useAccess();return <div className="account-controls"><span className="account-email" title={member.email}>{member.display_name||member.email}<small>{({viewer:'ผู้เข้าชม',editor:'ผู้แก้ไข',admin:'ผู้ดูแล'})[member.role]}</small></span><ThemeToggle/><button className="ghost" aria-label="ออกจากระบบ" title="ออกจากระบบ" onClick={()=>window.dispatchEvent(new Event('nexus-logout'))}><LogOut size={17}/></button></div>;}
export default function AccessGate({children}:{children:React.ReactNode}){const [member,setMember]=useState<Member|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[signingOut,setSigningOut]=useState(false);const generation=useRef(0),leaving=useRef(false);
 const refresh=useCallback(async()=>{if(leaving.current)return;const n=++generation.current;try{const r=await fetch('/api/session',{cache:'no-store'}),d=await r.json();if(n!==generation.current||leaving.current)return;if(!r.ok){setMember(null);setError(r.status===401?(new URLSearchParams(location.search).has('auth_error')?'เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่หรือติดต่อผู้ดูแล':''):d.error||'ตรวจสอบสิทธิ์ไม่สำเร็จ');}else{setMember(d.member);setError(new URLSearchParams(location.search).has('auth_error')?'เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่หรือติดต่อผู้ดูแล':'');}}catch{if(n!==generation.current||leaving.current)return;setMember(null);setError('ตรวจสอบสิทธิ์ไม่สำเร็จ กรุณาตรวจการเชื่อมต่อแล้วลองใหม่');}finally{setLoading(false);}},[]);
 useEffect(()=>{refresh();if(new URLSearchParams(location.search).has('auth_error')){setError('เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่หรือติดต่อผู้ดูแล');}const timer=setInterval(refresh,60000);const check=()=>{if(!document.hidden)refresh();};const logout=async()=>{leaving.current=true;++generation.current;setSigningOut(true);try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error();setMember(null);}catch{setMember(null);setError('ติดต่อบริการออกจากระบบไม่สำเร็จ กรุณาลองออกจากระบบอีกครั้ง');}finally{leaving.current=false;setSigningOut(false);}};window.addEventListener('focus',check);window.addEventListener('nexus-access-change',refresh);window.addEventListener('nexus-logout',logout);return()=>{clearInterval(timer);window.removeEventListener('focus',check);window.removeEventListener('nexus-access-change',refresh);window.removeEventListener('nexus-logout',logout);};},[refresh]);
 if(member?.status==='approved'&&!signingOut)return <Context.Provider value={{member,refresh}}><div key={member.id+member.role}>{children}</div></Context.Provider>;
 return <div className="access-page"><header><a className="access-brand" href="/"><Layers3 size={25}/>NEXUS<span>1.5</span></a><ThemeToggle/></header><main className="access-main"><section className="access-intro"><div className="eyebrow">A SHARED SPACE FOR GAME KNOWLEDGE</div><h1>ความรู้ทุกเกม<br/>ในพื้นที่เดียวกัน<span className="title-dot">.</span></h1><p>ค้นคำตอบ แบ่งปันวิธีเล่น และดูแลข้อมูลร่วมกัน<br/>เข้าถึงคลังความรู้ด้วยบัญชีที่ได้รับอนุมัติ</p><div className="access-pills"><span>ค้นทั้งหัวข้อและคำตอบ</span><span>ทุกเกมในที่เดียว</span><span>สิทธิ์ตามบทบาท</span></div></section><section className="access-card" aria-live="polite">{loading||signingOut?<><LoaderCircle className="spin"/><h2>{signingOut?'กำลังออกจากระบบ':'กำลังตรวจสอบสิทธิ์'}</h2></>:member?<><div className="access-symbol">{member.status==='pending'?<Clock3 size={30}/>:<ShieldCheck size={30}/>}</div><h2>{member.status==='pending'?'ส่งคำขอสิทธิ์แล้ว':'บัญชีนี้ถูกระงับสิทธิ์'}</h2><p>{member.email}</p><p>{member.status==='pending'?'ผู้ดูแลกำลังตรวจสอบคำขอ เมื่อได้รับอนุมัติหน้านี้จะเปิดคลังข้อมูลให้อัตโนมัติ':'กรุณาติดต่อผู้ดูแลเว็บไซต์เพื่อขอเปิดสิทธิ์อีกครั้ง'}</p><button className="primary" onClick={refresh}><RefreshCw size={16}/>ตรวจสอบสิทธิ์อีกครั้ง</button><button className="ghost" onClick={()=>window.dispatchEvent(new Event('nexus-logout'))}>ออกจากระบบ / เปลี่ยนบัญชี</button></>:<><div className="access-symbol"><ShieldCheck size={30}/></div><h2>เข้าใช้งานคลังความรู้</h2><p>ใช้บัญชี Google เพื่อเข้าสู่ระบบและส่งคำขอสิทธิ์ให้ผู้ดูแล</p><a href="/api/auth/start" className="google-login"><svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M21.6 12.2c0-.7-.1-1.4-.2-2.2H12v4.2h5.4a4.6 4.6 0 0 1-2 3v2.5h3.3c1.9-1.8 2.9-4.3 2.9-7.5ZM12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.5c-.9.6-2 .9-3.4.9-2.6 0-4.8-1.8-5.6-4.1H3v2.6A10 10 0 0 0 12 22ZM6.4 13.9a6 6 0 0 1 0-3.8V7.5H3a10 10 0 0 0 0 9l3.4-2.6ZM12 6c1.5 0 2.8.5 3.8 1.5l2.9-2.9A9.7 9.7 0 0 0 12 2a10 10 0 0 0-9 5.5l3.4 2.6C7.2 7.8 9.4 6 12 6Z"/></svg>ดำเนินการต่อด้วย Google</a><small>บัญชีใหม่จะอ่านข้อมูลได้หลังผู้ดูแลอนุมัติเท่านั้น</small></>}{error&&<div role="alert" className="error">{error}<button onClick={refresh}>ลองใหม่</button></div>}</section></main><footer>NEXUS GAME KNOWLEDGE · VERSION 1.5</footer></div>;
}
