'use client';
import {useState} from 'react';
import {protectedFetch} from '@/lib/client';
import type {Game} from './manage-panel';
import type {Entry} from '@/lib/game-data';
export default function DeletePanel({target,onDeleted,onCancel}:{target:{kind:'game';game:Game}|{kind:'entry';entry:Entry};onDeleted:(game:string,warning:string)=>void;onCancel:()=>void}){
 const [typed,setTyped]=useState(''),[cascade,setCascade]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const name=target.kind==='game'?target.game.name:target.entry.title;
 async function remove(){setBusy(true);setError('');try{const body=target.kind==='game'?{action:'game.delete',id:target.game.id,confirmName:typed,deleteEntries:cascade}:{action:'entry.delete',id:target.entry.id,confirm:true};const r=await protectedFetch('/api/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'ลบไม่สำเร็จ');onDeleted(target.kind==='game'?'all':target.entry.game,d.warning||'');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="delete-panel"><h3>ยืนยันลบ{target.kind==='game'?'เกม':'หัวข้อ'}</h3><strong>{name}</strong>{target.kind==='game'?<><p>เกมนี้มี {target.game.count} หัวข้อที่เผยแพร่ การลบจะนำเกมออกจากเมนูและลบรูปประจำเกม</p><label>พิมพ์ชื่อเกมเพื่อยืนยัน<input value={typed} disabled={busy} onChange={e=>setTyped(e.target.value)} autoComplete="off"/></label><label className="delete-check"><input type="checkbox" checked={cascade} disabled={busy} onChange={e=>setCascade(e.target.checked)}/>ลบหัวข้อทั้งหมดในเกมนี้ด้วย รวมถึงหัวข้อที่ยังไม่เผยแพร่</label><small>ถ้าไม่เลือก ระบบจะอนุญาตให้ลบเฉพาะเกมที่ไม่มีหัวข้อเท่านั้น</small></>:<p>หัวข้อนี้จะถูกลบออกจากคลังและผลการค้นหา</p>}<p>การลบนี้ย้อนกลับจากหน้าเว็บไม่ได้ กรุณาตรวจชื่อให้ถูกต้อง</p>{error&&<p role="alert" className="error">{error}</p>}<div className="image-actions"><button className="secondary" disabled={busy} onClick={onCancel}>ยกเลิก</button><button className="danger" disabled={busy||(target.kind==='game'&&typed!==name)} onClick={remove}>{busy?'กำลังลบ…':'ยืนยันการลบ'}</button></div></div>;
}
