'use client';
import {useEffect,useRef,useState} from 'react';
import {protectedFetch} from '@/lib/client';
import type {Game} from './manage-panel';
export default function ImagePanel({games,onSaved}:{games:Game[];onSaved:(id:string)=>void}){const [id,setId]=useState(games[0]?.id||''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const input=useRef<HTMLInputElement>(null);const game=games.find(g=>g.id===id);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function save(remove=false){if(remove&&!window.confirm('ลบรูปเกมนี้และกลับไปใช้ตัวอักษรย่อ?'))return;setBusy(true);setError('');setMessage('');try{const f=new FormData();f.set('game',id);if(file)f.set('file',file);const r=await protectedFetch('/api/game-image',remove?{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({game:id})}:{method:'POST',body:f});const d=await r.json();if(!r.ok)throw Error(d.error);setFile(null);if(input.current)input.current.value='';setMessage(remove?'ลบรูปแล้ว':'บันทึกรูปเกมแล้ว');onSaved(id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="editor"><label>เกม<select disabled={busy} value={id} onChange={e=>{setId(e.target.value);setFile(null);setMessage('');setError('');if(input.current)input.current.value='';}}>{games.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label>{preview||game?.image_path?<img className="upload-preview" src={preview||'/api/game-image?game='+encodeURIComponent(id)+'&v='+encodeURIComponent(game?.image_path||'')} alt={'ตัวอย่างรูป '+game?.name}/>:<div className="image-placeholder">ยังไม่มีรูปเกม</div>}<label>เลือกรูป PNG, JPEG หรือ WebP (ไม่เกิน 3 MB)<input ref={input} disabled={busy||!id} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];setError('');if(f&&f.size>3*1024*1024){setFile(null);setError('รูปภาพต้องไม่เกิน 3 MB');e.target.value='';}else setFile(f||null);}}/><small>แนะนำรูปสัดส่วนจัตุรัส รูปจะแสดงในเมนูเกมและหัวหน้าเกม</small></label>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<div className="image-actions"><button className="primary" disabled={busy||!file||!id} onClick={()=>save()}>{busy?'กำลังบันทึก…':'บันทึกรูปเกม'}</button><button className="secondary" disabled={busy||!game?.image_path} onClick={()=>save(true)}>ลบรูป</button></div></div>;
}
