'use client';
import {useEffect,useState} from 'react';
import type {Member} from '@/lib/auth';
import {protectedFetch} from '@/lib/client';
import {useAccess} from './access-gate';
export default function MembersPanel(){const {member:self}=useAccess(),[members,setMembers]=useState<Member[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){setBusy(true);setError('');try{const r=await protectedFetch('/api/members?page='+page),d=await r.json();if(!r.ok)throw Error(d.error);setMembers(d.members);setTotal(d.total);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[page]);
 async function save(m:Member){if(!window.confirm(`ยืนยันสิทธิ์ของ ${m.email} เป็น ${m.role} / ${m.status}?`))return;setBusy(true);setError('');setMessage('');try{const r=await protectedFetch('/api/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id,status:m.status,role:m.role})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage('บันทึกสิทธิ์แล้ว มีผลกับคำขอข้อมูลครั้งถัดไป');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="members-panel"><p className="muted">ผู้เข้าชม: อ่านข้อมูล · ผู้แก้ไข: จัดการเกม หัวข้อ และรูป · ผู้ดูแล: จัดการสิทธิ์เพิ่มได้</p><p className="muted">รออนุมัติและระงับสิทธิ์จะเข้าดูข้อมูลไม่ได้ ผู้ดูแลไม่สามารถเปลี่ยนสิทธิ์ตัวเองได้</p>{error&&<div role="alert" className="error">{error}<button onClick={load}>ลองใหม่</button></div>}{message&&<p role="status" className="success">{message}</p>}<div className="member-heading"><strong>สมาชิก {total} บัญชี</strong><button className="ghost" disabled={busy} onClick={load}>รีเฟรช</button></div>{members.map(m=><div className="member-row" key={m.id}><div><strong>{m.display_name||m.email}{m.id===self.id?' (คุณ)':''}</strong><p>{m.email}</p></div><label>สถานะ<select aria-label={'สถานะ '+m.email} disabled={busy||m.id===self.id} value={m.status} onChange={e=>setMembers(v=>v.map(x=>x.id===m.id?{...x,status:e.target.value as Member['status']}:x))}><option value="pending">รออนุมัติ</option><option value="approved">อนุมัติแล้ว</option><option value="blocked">ระงับสิทธิ์</option></select></label><label>บทบาท<select aria-label={'บทบาท '+m.email} disabled={busy||m.id===self.id} value={m.role} onChange={e=>setMembers(v=>v.map(x=>x.id===m.id?{...x,role:e.target.value as Member['role']}:x))}><option value="viewer">ผู้เข้าชม</option><option value="editor">ผู้แก้ไข</option><option value="admin">ผู้ดูแล</option></select></label><button className="primary" disabled={busy||m.id===self.id} onClick={()=>save(m)}>บันทึก</button></div>)}{!members.length&&!busy&&!error&&<p>ยังไม่มีคำขอสิทธิ์</p>}<nav className="pagination" aria-label="หน้าสมาชิก"><button disabled={busy||page===1} onClick={()=>setPage(n=>n-1)}>ก่อนหน้า</button><span>หน้า {page} / {Math.max(1,Math.ceil(total/50))}</span><button disabled={busy||page*50>=total} onClick={()=>setPage(n=>n+1)}>ถัดไป</button></nav></section>;
}
