'use client';
import {useEffect,useRef,useState,type RefObject} from 'react';
import {Search,ArrowRight,X,LoaderCircle,CornerDownLeft} from 'lucide-react';
import {protectedFetch} from '@/lib/client';
import type {Entry} from '@/lib/game-data';
import type {Game} from './manage-panel';
type Suggestion=Entry&{match_label?:string};
type Props={value:string;game:string;category:string;games:Game[];inputRef:RefObject<HTMLInputElement|null>;onChange:(q:string)=>void;onSubmit:(q:string)=>void;onOpen:(entry:Entry)=>void};
export default function SearchBox({value,game,category,games,inputRef,onChange,onSubmit,onOpen}:Props){
 const [items,setItems]=useState<Suggestion[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[focused,setFocused]=useState(false),[composing,setComposing]=useState(false),[active,setActive]=useState(-1),[resultKey,setResultKey]=useState('');
 const sequence=useRef(0);const key=JSON.stringify([value.trim(),game,category]);
 useEffect(()=>{const current=++sequence.current;setItems([]);setError('');setActive(-1);setBusy(false);if(composing||value.trim().length<2||!focused)return;const controller=new AbortController();const timer=setTimeout(async()=>{setBusy(true);try{const r=await protectedFetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q:value.trim(),game,category,suggest:true}),signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'โหลดคำแนะนำไม่สำเร็จ');if(current===sequence.current&&!controller.signal.aborted){setItems(d.entries);setResultKey(key);}}catch(e){if(!controller.signal.aborted&&current===sequence.current)setError((e as Error).message);}finally{if(current===sequence.current&&!controller.signal.aborted)setBusy(false);}},350);return()=>{clearTimeout(timer);controller.abort();};},[value,game,category,composing,focused,key]);
 const visible=focused&&!composing&&value.trim().length>=2;const suggestions=resultKey===key?items:[];
 function submit(){setFocused(false);onSubmit(value.trim());}
 function choose(entry:Entry){setFocused(false);setActive(-1);onOpen(entry);}
 return <div className="search-box"><form onSubmit={e=>{e.preventDefault();if(!composing)submit();}}><Search size={22}/><input ref={inputRef} role="combobox" aria-label="ค้นหาความรู้" aria-autocomplete="list" aria-expanded={visible} aria-controls={visible?'knowledge-suggestions':undefined} aria-activedescendant={visible&&active>=0?'suggestion-'+active:undefined} autoComplete="off" value={value} maxLength={500} onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)} onCompositionStart={()=>setComposing(true)} onCompositionEnd={()=>setComposing(false)} onChange={e=>{onChange(e.target.value);setFocused(true);}} onKeyDown={e=>{if(e.nativeEvent.isComposing||composing)return;if(e.key==='Escape'){e.preventDefault();setFocused(false);setActive(-1);}else if(e.key==='ArrowDown'){e.preventDefault();setFocused(true);setActive(i=>Math.min(i+1,suggestions.length-1));}else if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(-1,i-1));}else if(e.key==='Enter'&&visible&&active>=0&&suggestions[active]){e.preventDefault();choose(suggestions[active]);}}} placeholder="พิมพ์คำสำคัญ เช่น เติมเงิน รหัสผ่าน หรือ login…"/>{value&&<button type="button" className="clear-search" aria-label="ล้างคำค้น" onClick={()=>{onChange('');onSubmit('');inputRef.current?.focus();}}><X size={17}/></button>}<kbd>Ctrl K</kbd><button className="primary" type="submit">ค้นหา<ArrowRight size={17}/></button></form>
 {visible&&<div className="search-suggestions"><div className="suggestion-heading"><span>หัวข้อที่คุณอาจกำลังหา</span>{busy?<LoaderCircle size={15} className="spin"/>:<span>↑ ↓ เลือก · Enter เปิด</span>}</div><div id="knowledge-suggestions" role="listbox" aria-label="หัวข้อแนะนำ" aria-busy={busy}>{suggestions.map((entry,i)=><div role="option" aria-selected={i===active} id={'suggestion-'+i} key={entry.id} className={'suggestion-item '+(i===active?'selected':'')} onMouseDown={e=>e.preventDefault()} onMouseEnter={()=>setActive(i)} onClick={()=>choose(entry)}><Search size={16}/><div><strong>{entry.title}</strong><small>{games.find(g=>g.id===entry.game)?.name||entry.game} · {entry.match_label||'หัวข้อที่เกี่ยวข้อง'}</small></div><CornerDownLeft size={15}/></div>)}</div>{!busy&&!suggestions.length&&resultKey===key&&!error&&<p className="suggestion-empty">ยังไม่พบหัวข้อ ลองคำอื่นหรือคำที่สั้นลง</p>}{error&&<p className="suggestion-empty" role="status">{error}</p>}<button type="button" className="suggestion-all" onMouseDown={e=>e.preventDefault()} onClick={submit}>ดูผลการค้นหาทั้งหมด<ArrowRight size={15}/></button></div>}
 </div>;
}
