'use client';
import {useState,useRef} from 'react';
import {protectedFetch} from '@/lib/client';
import type {Game} from './manage-panel';
type Props={games:Game[];topics:{game:string;topic:string}[];onQueued:()=>void};
export default function TransferPanel({games,topics,onQueued}:Props){const [game,setGame]=useState(games[0]?.id||''),[mode,setMode]=useState<'file'|'url'|'export'>('file'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const fileInput=useRef<HTMLInputElement>(null);const [url,setUrl]=useState(''),[title,setTitle]=useState(''),[content,setContent]=useState(''),[topic,setTopic]=useState(topics.find(t=>t.game===game)?.topic||topics[0]?.topic||'ทั่วไป'),[warning,setWarning]=useState('');const choices=[...new Set(topics.map(t=>t.topic))];if(!choices.length)choices.push('ทั่วไป');if(!choices.includes(topic))choices.push(topic);
 async function perform(task:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function json(path:string,init:RequestInit){const r=await protectedFetch(path,init);const d=await r.json();if(!r.ok)throw Error(d.error||'ทำรายการไม่สำเร็จ');return d;}
 const post=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 function queued(d:any){setMessage(`ส่งร่างใหม่ ${d.added} รายการ · ข้ามรายการซ้ำ ${d.skipped} รายการ ไปที่แท็บ “รอตรวจสอบ” เพื่ออนุมัติ`);setPreview(null);onQueued();}
 async function importFile(commit=false){if(!file)return;await perform(async()=>{const f=new FormData();f.set('file',file);f.set('game',game);f.set('mode',commit?'commit':'preview');if(commit)f.set('confirmed','true');const d=await json('/api/transfer',{method:'POST',body:f});if(commit){queued(d);setFile(null);if(fileInput.current)fileInput.current.value='';}else setPreview(d);});}
 async function fetchArticle(){await perform(async()=>{const d=await json('/api/source',post({action:'fetch',game,url}));setTitle(d.title);setContent(d.content);setUrl(d.source_url);setTopic(d.topic);setWarning(d.warning);setPreview(null);});}
 async function article(commit=false){await perform(async()=>{const d=await json('/api/source',post({action:commit?'submit':'preview',game,confirmed:commit,row:{title,content,topic,source_url:url}}));if(commit)queued(d);else setPreview(d);});}
 async function download(format:string){await perform(async()=>{const r=await protectedFetch('/api/transfer?game='+encodeURIComponent(game)+'&format='+format);if(!r.ok){const d=await r.json();throw Error(d.error);}const blob=await r.blob(),link=document.createElement('a'),local=URL.createObjectURL(blob);link.href=local;link.download=r.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1]||`nexus-${game}.${format}`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(local),1000);setMessage('ดาวน์โหลดไฟล์แล้ว');});}
 function resetPreview(){setPreview(null);setMessage('');}
 return <div className="editor"><label>เกมปลายทาง / เกมที่ส่งออก<select value={game} disabled={busy} onChange={e=>{setGame(e.target.value);setTopic(topics.find(t=>t.game===e.target.value)?.topic||choices[0]);resetPreview();setError('');}}><option value="" disabled>เลือกเกม</option>{games.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><div className="transfer-modes">{[['file','Import ไฟล์'],['url','นำเข้าจากลิงก์'],['export','Export']].map(([id,label])=><button key={id} className={mode===id?'primary':'secondary'} disabled={busy} onClick={()=>{setMode(id as typeof mode);resetPreview();setError('');}}>{label}</button>)}</div>
 {mode==='file'&&<><p className="muted">JSON หรือ CSV UTF-8 ไม่เกิน 3 MB / 5,000 รายการ นำเข้าเป็นร่างรอผู้ดูแลอนุมัติทั้งหมด ไม่เขียนทับหัวข้อเดิม</p><label>ไฟล์ข้อมูล<input ref={fileInput} type="file" accept=".json,.csv,application/json,text/csv" disabled={busy} onChange={e=>{const f=e.target.files?.[0]||null;resetPreview();setError('');if(f&&f.size>3*1024*1024){setError('ไฟล์ต้องไม่เกิน 3 MB');setFile(null);e.target.value='';}else setFile(f);}}/></label><p className="muted">CSV ต้องมี title, content ส่วน topic, tags, summary, source_url, source_id เป็นตัวเลือก ดาวน์โหลด JSON/CSV ของเกมนี้เพื่อใช้เป็นรูปแบบตัวอย่างได้</p><button className="secondary" disabled={busy||!file||!game} onClick={()=>importFile()}>ตรวจไฟล์ก่อนนำเข้า</button></>}
 {mode==='url'&&<><p className="muted">อ่านบทความจากโดเมนที่อนุญาต (เริ่มต้น tosm.exe.in.th) ไม่ใช้ AI หากเว็บโหลดเนื้อหาด้วย JavaScript ให้วางข้อความต้นฉบับเองพร้อมลิงก์อ้างอิง</p><label>ลิงก์บทความ<input type="url" value={url} maxLength={2000} disabled={busy} onChange={e=>{setUrl(e.target.value);resetPreview();}} placeholder="https://tosm.exe.in.th/news/…"/></label><button className="secondary" disabled={busy||!url||!game} onClick={fetchArticle}>ดึงข้อความจากลิงก์</button>{warning&&<p className="import-warning">{warning}</p>}<label>หัวข้อ<input value={title} maxLength={300} disabled={busy} onChange={e=>{setTitle(e.target.value);resetPreview();}}/></label><label>หมวดหมู่ที่เสนอ<select value={topic} disabled={busy} onChange={e=>{setTopic(e.target.value);resetPreview();}}>{choices.map(t=><option key={t}>{t}</option>)}</select></label><label>ข้อความต้นฉบับ / ข้อความที่จะเสนอ<textarea rows={8} value={content} maxLength={20000} disabled={busy} onChange={e=>{setContent(e.target.value);resetPreview();}}/></label><small>{content.length.toLocaleString()} / 20,000 ตัวอักษร · ตรวจเนื้อหาและลิงก์ก่อนส่ง ไม่ถือว่าบทความทุกชิ้นเป็นวิธีแก้ปัญหาที่รับรองแล้ว</small><button className="secondary" disabled={busy||!url||!title.trim()||!content.trim()||!game} onClick={()=>article()}>ตรวจข้อมูลซ้ำก่อนส่งร่าง</button></>}
 {mode==='export'&&<><p>ส่งออกหัวข้อทั้งหมดของเกมที่เลือก รวมรายการที่ยังไม่เผยแพร่ในตารางหัวข้อ โดยไม่รวมร่างรออนุมัติ บัญชีสมาชิก หรือไฟล์รูปเกม</p><div className="image-actions"><button className="primary" disabled={busy||!game} onClick={()=>download('json')}>ดาวน์โหลด JSON</button><button className="secondary" disabled={busy||!game} onClick={()=>download('csv')}>ดาวน์โหลด CSV</button></div><p className="muted">JSON มีข้อมูลชื่อ/รายละเอียดเกมและหัวข้อ; เมื่อนำกลับเข้า เลือกเกมปลายทางเอง และระบบสร้างร่างให้ตรวจใหม่</p></>}
 {preview&&<div className="import-preview"><h3>ตรวจรายการก่อนส่ง</h3>{preview.sourceGame&&<p>เกมในไฟล์: {preview.sourceGame} → ปลายทาง: {games.find(g=>g.id===game)?.name}</p>}<p>ทั้งหมด {preview.total} · ใหม่ {preview.newCount} · ซ้ำ {preview.duplicateCount}</p><ol>{preview.preview.map((r:any)=><li key={r.row}><span>{r.title}</span><small>{r.topic} · {r.duplicate?'ข้ามรายการซ้ำ':'รออนุมัติ'}</small></li>)}</ol>{preview.total>50&&<small>แสดงตัวอย่าง 50 รายการแรก ตรวจข้อมูลทั้งไฟล์แล้ว</small>}<button className="primary" disabled={busy||!preview.newCount} onClick={()=>mode==='file'?importFile(true):article(true)}>ยืนยันส่งร่างให้ผู้ดูแลตรวจ</button><small>ตรวจซ้ำอีกครั้งตอนบันทึก หากมีผู้นำเข้าพร้อมกัน จำนวนจริงอาจเปลี่ยน</small></div>}
 {busy&&<p role="status">กำลังดำเนินการ…</p>}{error&&<p role="alert" className="error import-error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}</div>;
}
