import {requireAccess} from '@/lib/auth';
import {sameOrigin,reply,fail,AppError,db,must} from '@/lib/server';
import {parseImport,exportCSV,MAX_FILE} from '@/lib/transfer';
import {getGame,gameRows,duplicatePreview} from '@/lib/import-data';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=60;
export async function GET(req:Request){try{const a=await requireAccess('editor'),u=new URL(req.url),id=u.searchParams.get('game')||'',format=u.searchParams.get('format')||'json';if(!['json','csv'].includes(format))throw new AppError('รูปแบบ export ไม่ถูกต้อง',400);const game=await getGame(id,a.token),rows=await gameRows(id,a.token);await requireAccess('editor');const data=format==='csv'?exportCSV(rows):JSON.stringify({format:'nexus-game-export',version:'1.5',exported_at:new Date().toISOString(),game,entries:rows},null,2);if(Buffer.byteLength(data)>MAX_FILE)throw new AppError('ข้อมูลเกิน 3 MB กรุณาแบ่งชุดข้อมูลก่อนส่งออก',413);return new Response(data,{headers:{'Content-Type':format==='csv'?'text/csv; charset=utf-8':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="nexus-${id}-${new Date().toISOString().slice(0,10)}.${format}"`,'Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff'}});}catch(e){return fail(e);}}
export async function POST(req:Request){try{sameOrigin(req);const a=await requireAccess('editor');if(Number(req.headers.get('content-length'))>MAX_FILE+65536)throw new AppError('ไฟล์ต้องไม่เกิน 3 MB',413);const f=await req.formData(),file=f.get('file'),game=String(f.get('game')||''),mode=f.get('mode');await getGame(game,a.token);if(!(file instanceof File)||file.size>MAX_FILE)throw new AppError('กรุณาเลือกไฟล์ไม่เกิน 3 MB',400);const bytes=await file.arrayBuffer();let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw new AppError('กรุณาบันทึกไฟล์ CSV เป็น UTF-8 เพื่อรองรับภาษาไทย',400);}const {rows,sourceGame}=parseImport(text,file.name);
 if(mode==='preview')return reply({...await duplicatePreview(game,a.token,rows),sourceGame});
 if(mode!=='commit'||f.get('confirmed')!=='true')throw new AppError('กรุณาตรวจและยืนยันการนำเข้า',400);
 const r=await must(await db('rpc/nexus_enqueue',{method:'POST',body:JSON.stringify({p_game:game,p_rows:rows,p_kind:'file',p_source:null})},a.token),'drafts.import');return reply(await r.json());}catch(e){return fail(e);}}
