import {resolve4} from 'node:dns/promises';
import {request} from 'node:https';
import {isIP} from 'node:net';
import {AppError} from './server';
export function sourceURL(raw:string){let u:URL;try{u=new URL(raw);}catch{throw new AppError('ลิงก์ไม่ถูกต้อง',400);}const allowed=(process.env.IMPORT_ALLOWED_HOSTS||'tosm.exe.in.th').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443')||isIP(u.hostname)||!allowed.includes(u.hostname.toLowerCase()))throw new AppError('รองรับเฉพาะ HTTPS จากโดเมนที่ตั้งไว้ใน IMPORT_ALLOWED_HOSTS',400);u.hash='';return u;}
export function publicIPv4(ip:string){if(isIP(ip)!==4)return false;const [a,b,c]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===168||b===0||b===88))||(a===198&&(b===18||b===19||(b===51&&c===100)))||(a===203&&b===0&&c===113));}
export async function fetchSource(raw:string,hop=0):Promise<{html:string;url:string}>{if(hop>2)throw new AppError('เว็บไซต์เปลี่ยนเส้นทางมากเกินไป',400);const u=sourceURL(raw);let timer:ReturnType<typeof setTimeout>|undefined;let addresses:string[];try{addresses=await Promise.race([resolve4(u.hostname),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('DNS timeout')),3000);})]);}catch{throw new AppError('หาเว็บไซต์ไม่พบ ลองตรวจลิงก์หรือวางข้อความเอง',502);}finally{clearTimeout(timer);}if(!addresses.length||addresses.some(ip=>!publicIPv4(ip)))throw new AppError('ไม่อนุญาตให้เชื่อมต่อที่อยู่เครือข่ายภายใน',400);
 const result=await new Promise<{html?:string;redirect?:string}>((resolve,reject)=>{const req=request(u,{method:'GET',family:4,lookup:((_host:unknown,options:any,cb:any)=>{if(options?.all)cb(null,[{address:addresses[0],family:4}]);else cb(null,addresses[0],4);}) as any,headers:{Accept:'text/html','Accept-Encoding':'identity','User-Agent':'Nexus-Knowledge-Importer/1.5'},timeout:10000},res=>{const status=res.statusCode||0;if([301,302,303,307,308].includes(status)){res.resume();if(!res.headers.location){reject(new AppError('เว็บเปลี่ยนเส้นทางโดยไม่มีปลายทาง',502));return;}resolve({redirect:new URL(res.headers.location,u).href});return;}if(status!==200){res.resume();reject(new AppError(`เว็บต้นทางตอบ HTTP ${status} กรุณาวางข้อความเองหรือลองใหม่`,502));return;}if(!String(res.headers['content-type']).includes('text/html')||!['identity',''].includes(String(res.headers['content-encoding']||''))){res.resume();reject(new AppError('หน้านี้ไม่ใช่ HTML ที่รองรับ กรุณาวางข้อความเอง',400));return;}let total=0;const chunks:Buffer[]=[];res.on('data',(chunk:Buffer)=>{total+=chunk.length;if(total>1024*1024){req.destroy(new AppError('หน้าเว็บมีขนาดเกิน 1 MB กรุณาวางข้อความเฉพาะบทความ',413));return;}chunks.push(chunk);});res.on('end',()=>{try{resolve({html:new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks))});}catch{reject(new AppError('เว็บนี้ไม่ได้ใช้ข้อความ UTF-8 กรุณาวางข้อความเองเพื่อรักษาภาษาไทย',422));}});res.on('error',reject);});const deadline=setTimeout(()=>req.destroy(new AppError('เว็บต้นทางตอบช้า กรุณาลองใหม่',504)),12000);req.on('close',()=>clearTimeout(deadline));req.on('timeout',()=>req.destroy(new AppError('เว็บต้นทางตอบช้า',504)));req.on('error',e=>reject(e instanceof AppError?e:new AppError('อ่านเว็บไซต์ไม่สำเร็จ กรุณาวางข้อความเอง',502)));req.end();});if(result.redirect)return fetchSource(result.redirect,hop+1);return {html:result.html||'',url:u.href};}
function entities(s:string){const known:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};return s.replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(_,key:string)=>{if(key[0]==='#'){const n=key[1].toLowerCase()==='x'?parseInt(key.slice(2),16):parseInt(key.slice(1),10);return n>0&&n<=0x10ffff&&!(n>=0xd800&&n<=0xdfff)?String.fromCodePoint(n):'';}return known[key.toLowerCase()]||'';});}
export function extractArticle(html:string){
 // Linear tag scan: untrusted malformed HTML cannot trigger quadratic strip-tag regexes.
 const buffers:Record<string,string[]>={body:[],main:[],article:[],h1:[],title:[]};const inside:Record<string,number>={head:0,main:0,article:0,h1:0,title:0};const ignored=new Set(['script','style','noscript','svg','nav','footer','header','aside']);let skip='',depth=0,last=0;
 function append(text:string){if(skip)return;if(inside.title)buffers.title.push(text);if(inside.h1)buffers.h1.push(text);if(!inside.head){buffers.body.push(text);if(inside.main)buffers.main.push(text);if(inside.article)buffers.article.push(text);}}
 const tag=/<[^<>]*>/g;let match:RegExpExecArray|null;while((match=tag.exec(html))){append(html.slice(last,match.index));last=tag.lastIndex;const parts=match[0].match(/^<\s*(\/?)\s*([a-z][a-z0-9]*)/i);if(!parts)continue;const closing=!!parts[1],name=parts[2].toLowerCase();if(skip){if(name===skip){depth+=closing?-1:1;if(depth<=0)skip='';}continue;}if(ignored.has(name)&&!closing){skip=name;depth=1;continue;}if(name in inside)inside[name]=Math.max(0,inside[name]+(closing?-1:1));if(['br','p','div','li','tr','h1','h2','h3','h4','h5','h6'].includes(name))append('\n');else append(' ');}append(html.slice(last));
 const plain=(parts:string[])=>entities(parts.join('')).replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim();const title=plain(buffers.h1.length?buffers.h1:buffers.title).slice(0,300),content=plain(buffers.article.length?buffers.article:buffers.main.length?buffers.main:buffers.body);if(!title||content.length<80)throw new AppError('ดึงเนื้อหาบทความไม่ครบ เว็บไซต์อาจโหลดด้วย JavaScript กรุณาคัดลอกข้อความต้นฉบับมาวางและตรวจสอบก่อนส่งร่าง',422);return {title,content:content.slice(0,20000),warning:content.length>20000?'ตัดข้อความที่ 20,000 ตัวอักษร กรุณาตรวจเทียบต้นฉบับ':'ข้อความอาจมีเมนูหรือส่วนอื่นติดมา กรุณาตรวจเทียบต้นฉบับก่อนส่งร่าง'};
}
export function suggestTopic(text:string,topics:string[]){const groups:[RegExp,string[]][]=[[/เติมเงิน|ชำระ|payment|top.?up/i,['Payment','การเติมเงิน']],[/บัญชี|รหัสผ่าน|account|login/i,['Account','บัญชีผู้เล่น']],[/แพทช์|อัปเดต|กิจกรรม|event|patch/i,['Event & News','กิจกรรมและข่าวสาร']],[/error|ปัญหา|ติดตั้ง|ดาวน์โหลด/i,['Technical Support','ปัญหาทางเทคนิค']]];for(const [pattern,names] of groups)if(pattern.test(text)){const found=topics.find(t=>names.includes(t));if(found)return found;}return topics[0]||'ทั่วไป';}
