import {AppError} from './server';
export type ImportRow={title:string;content:string;summary:string;topic:string;category:string;tags:string[];source_url:string|null;source_id:string|null};
export const MAX_FILE=3*1024*1024;
export function safeSource(value:unknown){if(value===undefined||value===null||value==='')return null;if(typeof value!=='string'||value.length>2000)throw new AppError('ลิงก์อ้างอิงไม่ถูกต้อง',400);try{const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error();return u.href;}catch{throw new AppError('ลิงก์อ้างอิงต้องเป็น http หรือ https',400);}}
export function validateRow(value:unknown,index=0):ImportRow{const prefix=`รายการ ${index+1}: `;if(!value||typeof value!=='object'||Array.isArray(value))throw new AppError(prefix+'รูปแบบไม่ถูกต้อง',400);const r=value as Record<string,unknown>;
 const field=(k:string,max:number,required=false)=>{if(r[k]!==undefined&&r[k]!==null&&typeof r[k]!=='string')throw new AppError(prefix+k+' ต้องเป็นข้อความ',400);const v=String(r[k]??'').trim();if((required&&!v)||v.length>max)throw new AppError(prefix+k+' ว่างหรือยาวเกิน '+max+' ตัวอักษร',400);return v;};
 const title=field('title',300,true),content=field('content',20000,true),topic=field('topic',80)||'ทั่วไป';let tags:unknown=r.tags??[];if(typeof tags==='string'){try{tags=JSON.parse(tags);}catch{tags=String(tags).split('|').map(t=>t.trim()).filter(Boolean);}}if(!Array.isArray(tags)||tags.length>30||tags.some(t=>typeof t!=='string'||t.length>100))throw new AppError(prefix+'tags ต้องเป็นรายการข้อความไม่เกิน 30 คำ',400);
 return {title,content,topic,summary:field('summary',500)||content.slice(0,160),category:['ไอเทม','ตัวละคร','คู่มือ'].includes(String(r.category))?String(r.category):'คู่มือ',tags:tags as string[],source_url:safeSource(r.source_url),source_id:field('source_id',200)||null};}
export function fingerprint(r:{title:string;content:string}){return r.title.trim().toLowerCase()+'\n'+r.content.trim().toLowerCase();}
const dangerous=(s:string)=>/^[\s\uFEFF]*[=+\-@]/u.test(s)||/^[\t\r\n]/.test(s);
function csvCell(value:string){const s=dangerous(value)||value.startsWith("'")?"'"+value:value;return '"'+s.replaceAll('"','""')+'"';}
function unescapeCell(s:string){return s.startsWith("'")&&(dangerous(s.slice(1))||s.slice(1).startsWith("'"))?s.slice(1):s;}
export function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false,endedQuote=false;const s=text.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(c==='"'){if(s[i+1]==='"'){cell+='"';i++;}else{quoted=false;endedQuote=true;}}else cell+=c;}else if(c==='"'){if(cell||endedQuote)throw new AppError('CSV มีเครื่องหมายคำพูดไม่ถูกต้อง',400);quoted=true;}else if(c===','){row.push(unescapeCell(cell));cell='';endedQuote=false;}else if(c==='\n'||c==='\r'){if(c==='\r'&&s[i+1]==='\n')i++;row.push(unescapeCell(cell));if(row.some(x=>x!==''))rows.push(row);row=[];cell='';endedQuote=false;}else{if(endedQuote)throw new AppError('CSV มีข้อความหลังเครื่องหมายปิดคำพูด',400);cell+=c;}}if(quoted)throw new AppError('CSV ปิดเครื่องหมายคำพูดไม่ครบ',400);if(cell||row.length||endedQuote){row.push(unescapeCell(cell));if(row.some(x=>x!==''))rows.push(row);}if(rows.length<2)throw new AppError('CSV ต้องมีหัวคอลัมน์และข้อมูลอย่างน้อยหนึ่งรายการ',400);const header=rows.shift()!.map(x=>x.trim());if(new Set(header).size!==header.length||!header.includes('title')||!header.includes('content'))throw new AppError('CSV ต้องมีคอลัมน์ title และ content และชื่อคอลัมน์ไม่ซ้ำ',400);return rows.map((r,i)=>{if(r.length!==header.length)throw new AppError(`CSV รายการ ${i+1} มีจำนวนคอลัมน์ไม่ครบ`,400);return Object.fromEntries(header.map((h,j)=>[h,r[j]]));});}
export function parseImport(text:string,name:string){if(Buffer.byteLength(text,'utf8')>MAX_FILE)throw new AppError('ไฟล์ต้องไม่เกิน 3 MB',413);let raw:unknown,sourceGame='';if(name.toLowerCase().endsWith('.csv'))raw=parseCSV(text);else if(name.toLowerCase().endsWith('.json')){try{const data=JSON.parse(text.replace(/^\uFEFF/,''));raw=Array.isArray(data)?data:data.entries;sourceGame=typeof data.game?.name==='string'?data.game.name:'';}catch{throw new AppError('JSON ไม่ถูกต้อง',400);}}else throw new AppError('รองรับไฟล์ .json และ .csv เท่านั้น',400);if(!Array.isArray(raw)||!raw.length||raw.length>5000)throw new AppError('ไฟล์ต้องมี 1–5,000 รายการ',400);const errors:string[]=[],rows:ImportRow[]=[];raw.forEach((r,i)=>{try{rows.push(validateRow(r,i));}catch(e){if(errors.length<20)errors.push((e as Error).message);}});if(errors.length)throw new AppError(errors.join('\n')+'\nยังไม่มีข้อมูลใดถูกนำเข้า',400);return {rows,sourceGame};}
export function exportCSV(rows:ImportRow[]){const keys:(keyof ImportRow)[]=['title','content','summary','topic','category','tags','source_url','source_id'];return '\uFEFF'+keys.join(',')+'\r\n'+rows.map(r=>keys.map(k=>csvCell(k==='tags'?JSON.stringify(r[k]):String(r[k]??''))).join(',')).join('\r\n');}
