import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'nexus-tests-'));
const nativeFetch=globalThis.fetch;const saved={...process.env};
const compile=async(src,name)=>{let s=await fs.readFile(new URL('../'+src,import.meta.url),'utf8');s=s.replaceAll("'@/lib/server'","'./server.mjs'").replaceAll("'@/lib/game-data'","'./data.mjs'");await fs.writeFile(path.join(tmp,name),ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);};
const req=(body,key='')=>new Request('http://nexus.local/api',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify(body)});
try{
 await compile('lib/server.ts','server.mjs');await compile('lib/game-data.ts','data.mjs');await compile('app/api/search/route.ts','search.mjs');await compile('app/api/manage/route.ts','manage.mjs');await compile('app/api/catalog/route.ts','catalog.mjs');
 const {POST:search}=await import(pathToFileURL(path.join(tmp,'search.mjs')));const {POST:manage}=await import(pathToFileURL(path.join(tmp,'manage.mjs')));const {GET:catalog}=await import(pathToFileURL(path.join(tmp,'catalog.mjs')));
 delete process.env.SUPABASE_URL;delete process.env.SUPABASE_PUBLISHABLE_KEY;delete process.env.OPENAI_API_KEY;delete process.env.SUPABASE_SECRET_KEY;delete process.env.ADMIN_ACCESS_KEY;
 const demo=await (await search(req({game:'TOSM'}))).json();assert.equal(demo.total,3);assert.equal(demo.connected,false);assert.equal((await search(req(null))).status,400);assert.equal((await search(req({q:'x'.repeat(501)}))).status,400);assert.equal((await manage(req({action:'game.create'}))).status,503);assert.equal((await (await catalog()).json()).adminReady,false);
 console.log('PASS: demo and validation; administration fails closed without configuration');
 process.env.SUPABASE_URL='https://mock.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='publishable-test';
 let queries=[];globalThis.fetch=async(input,init)=>{const u=new URL(input);queries.push(u);assert.equal(init.headers.Prefer,'count=exact');assert.equal(u.searchParams.get('published'),'eq.true');assert.match(u.searchParams.get('order'),/id.asc/);const limit=Number(u.searchParams.get('limit')),offset=Number(u.searchParams.get('offset'));return Response.json(Array.from({length:Math.max(0,Math.min(limit,360-offset))},(_,i)=>({id:'id-'+(i+offset),game:'TOSM',title:'Question',content:'Answer',tags:[]})),{headers:{'Content-Range':`${offset}-${Math.min(offset+limit,360)-1}/360`}});};
 const ids=new Set();for(let page=1;page<=15;page++){const d=await (await search(req({page,pageSize:24,game:'TOSM'}))).json();assert.equal(d.total,360);assert.equal(d.entries.length,24);d.entries.forEach(e=>ids.add(e.id));}assert.equal(ids.size,360);
 await search(req({page:2,pageSize:48,game:'new-game',category:'Account',q:'faq_to_001'}));let u=queries.at(-1);assert.equal(u.searchParams.get('game'),'eq.new-game');assert.equal(u.searchParams.get('topic'),'eq.Account');assert.equal(u.searchParams.get('offset'),'48');assert.match(u.searchParams.get('or'),/faq_to_001/);
 console.log('PASS: all 360 records across 15 pages without duplicates; dynamic game, topic and FAQ ID search');
 process.env.SUPABASE_SECRET_KEY='server-secret-test';process.env.ADMIN_ACCESS_KEY='admin-key-for-tests-only-123456';let writes=0;
 globalThis.fetch=async(input,init)=>{writes++;const u=new URL(input);const headers=new Headers(init.headers);assert.equal(headers.get('apikey'),'server-secret-test');assert.equal(init.method,'POST');const b=JSON.parse(init.body);if(u.pathname.endsWith('games')){assert.equal(b.id,'new-game');return Response.json([{...b}]);}assert.equal(b.game,'new-game');assert.equal(b.published,true);return Response.json([{id:'new-entry',...b}]);};
 assert.equal((await manage(req({action:'game.create',id:'new-game',name:'New Game'},'wrong'))).status,401);assert.equal(writes,0);assert.equal((await manage(req({action:'verify'},process.env.ADMIN_ACCESS_KEY))).status,200);assert.equal(writes,0);
 assert.equal((await manage(req({action:'game.create',id:'new-game',name:'New Game',color:'blue'},process.env.ADMIN_ACCESS_KEY))).status,200);
 assert.equal((await manage(req({action:'entry.create',game:'new-game',title:'Question',content:'Answer',topic:'Basics'},process.env.ADMIN_ACCESS_KEY))).status,200);assert.equal(writes,2);
 assert.equal((await manage(req({action:'game.create',id:'bad.id',name:'Bad'},process.env.ADMIN_ACCESS_KEY))).status,400);
 console.log('PASS: unauthorized writes rejected; authenticated game and entry creation; invalid identifiers rejected');
 globalThis.fetch=async()=>new Response('unavailable',{status:500});assert.equal((await search(req({q:'test'}))).status,502);
 console.log('PASS: upstream errors reported');
}finally{globalThis.fetch=nativeFetch;for(const key of ['SUPABASE_URL','SUPABASE_PUBLISHABLE_KEY','SUPABASE_SECRET_KEY','ADMIN_ACCESS_KEY','OPENAI_API_KEY']){if(saved[key]===undefined)delete process.env[key];else process.env[key]=saved[key];}await fs.rm(tmp,{recursive:true,force:true});}
