// Run against a local build: NEXUS_TEST_URL=http://127.0.0.1:3155 node scripts/ui-test.mjs
// Playwright is a development-only tool; all API traffic is intercepted with fixtures.
import {createRequire} from 'node:module';const {chromium}=createRequire(import.meta.url)('playwright');import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});const base=process.env.NEXUS_TEST_URL||'http://127.0.0.1:3155';let role='admin',state='pending',enqueued=false,approvals=0;const errors=[];
const entry={id:'13000000-0000-4000-a000-000000000001',game:'TOSM',title:'คำถามเดิม',content:'คำตอบเดิม',summary:'คำตอบเดิม',topic:'Account',category:'คู่มือ',tags:[],updated_at:'2026-09-10'};
const payload={title:'หัวข้อนำเข้า',content:'ข้อความต้นฉบับที่จะให้ผู้ดูแลตรวจสอบ',topic:'Account',summary:'ข้อความต้นฉบับ',category:'คู่มือ',tags:[],source_url:'https://tosm.exe.in.th/news/example',source_id:null};
try{const context=await browser.newContext({viewport:{width:1440,height:1100}});await context.route('**/api/**',async route=>{const u=new URL(route.request().url()),r=route.request();let data={};if(r.headers()['content-type']?.includes('application/json'))data=r.postDataJSON();const respond=(body,status=200,headers={})=>route.fulfill({status,contentType:'application/json',headers,body:JSON.stringify(body)});
 if(u.pathname==='/api/session')return role==='anonymous'?respond({error:'Login required'},401):respond({member:{id:'owner',email:'owner@example.invalid',display_name:'QA Admin',role,status:'approved'}});
 if(u.pathname==='/api/catalog')return respond({games:[{id:'TOSM',name:'TOSM',description:'QA game',color:'teal',count:1}],topics:[{game:'TOSM',topic:'Account',count:1}],total:1,connected:true,ai:false,adminReady:true});
 if(u.pathname==='/api/search')return respond({entries:[entry],total:1,page:1,pageSize:24,terms:[],sources:[]});
 if(u.pathname==='/api/transfer'&&r.method()==='GET')return route.fulfill({status:200,contentType:'text/csv; charset=utf-8',headers:{'Content-Disposition':'attachment; filename="nexus-TOSM.csv"'},body:'\uFEFFtitle,content\r\nคำถาม,คำตอบ'});
 if(u.pathname==='/api/transfer'){const committing=r.postData()?.includes('commit');if(committing){enqueued=true;return respond({added:1,skipped:0});}return respond({total:1,newCount:1,duplicateCount:0,sourceGame:'',preview:[{row:1,title:'หัวข้อนำเข้า',topic:'Account',duplicate:false}]});}
 if(u.pathname==='/api/drafts'&&r.method()==='GET')return respond({drafts:enqueued&&(u.searchParams.get('status')===state)?[{id:entry.id,game:'TOSM',payload,status:state,source_kind:'file',source_url:null,created_at:'2026-09-10',reviewed_at:null,review_note:''}]:[],total:enqueued&&state==='pending'?1:0});
 if(u.pathname==='/api/drafts'){state='approved';approvals++;return respond({status:'approved'});}
 if(u.pathname==='/api/source')return respond({error:'เว็บไซต์โหลดด้วย JavaScript กรุณาวางข้อความเอง'},422);
 return respond({error:'unexpected mocked route'},500);
 });const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByRole('button',{name:'จัดการ',exact:true}).click();await page.getByRole('tab',{name:'Import / Export',exact:true}).click();await page.getByLabel('ไฟล์ข้อมูล', {exact:true}).setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from('title,content\nหัวข้อนำเข้า,ข้อความไทย','utf8')});await page.getByRole('button',{name:'ตรวจไฟล์ก่อนนำเข้า'}).click();await page.getByRole('button',{name:'ยืนยันส่งร่างให้ผู้ดูแลตรวจ'}).click();await page.getByText(/ส่งร่างใหม่ 1 รายการ/).waitFor();assert.ok(enqueued);
 await page.getByRole('tab',{name:'รอตรวจสอบ',exact:true}).click();await page.getByRole('button',{name:/หัวข้อนำเข้า/}).click();await page.getByLabel('หัวข้อ',{exact:true}).fill('หัวข้อที่ผู้ดูแลแก้ไข');await page.getByRole('button',{name:'อนุมัติเผยแพร่',exact:true}).click();await page.getByRole('button',{name:'ยืนยันอนุมัติ',exact:true}).click();await page.getByText('บันทึกแล้ว: อนุมัติแล้ว',{exact:true}).waitFor();assert.equal(approvals,1);
 await page.getByRole('tab',{name:'Import / Export',exact:true}).click();await page.getByRole('button',{name:'Export',exact:true}).click();const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'ดาวน์โหลด CSV',exact:true}).click();const download=await downloaded;assert.equal(download.suggestedFilename(),'nexus-TOSM.csv');
 await page.getByRole('button',{name:'นำเข้าจากลิงก์',exact:true}).click();await page.getByLabel('ลิงก์บทความ',{exact:true}).fill('https://tosm.exe.in.th/news/test');await page.getByRole('button',{name:'ดึงข้อความจากลิงก์',exact:true}).click();await page.getByText('เว็บไซต์โหลดด้วย JavaScript กรุณาวางข้อความเอง',{exact:true}).waitFor();await page.getByLabel('ข้อความต้นฉบับ / ข้อความที่จะเสนอ',{exact:true}).fill('วางข้อความด้วยตนเองได้หลังดึงเว็บไม่สำเร็จ');
 await page.setViewportSize({width:390,height:844});assert.ok(await page.getByRole('tab',{name:'Import / Export',exact:true}).isVisible());await page.screenshot({path:'/tmp/nexus-v15-mobile.png',fullPage:true});
 role='viewer';await page.goto(base);await page.getByRole('heading',{name:/คลังความรู้เกม/}).waitFor();assert.equal(await page.getByRole('button',{name:'จัดการ',exact:true}).count(),0);role='anonymous';await page.goto(base);await page.getByText('ดำเนินการต่อด้วย Google',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS browser: file preview → pending draft → admin edit/approve, CSV download, URL failure/manual fallback, mobile tabs, viewer/anonymous gate, no page errors');await context.close();
}finally{await browser.close();}
