import {requireAccess} from '@/lib/auth';
import {db,must,supabase,reply,fail,sameOrigin,AppError,jsonBody} from '@/lib/server';
import {imageType} from '@/lib/image-validation';
export const dynamic='force-dynamic';
async function game(id:string,token:string){if(!/^[A-Za-z0-9_-]{1,48}$/.test(id))throw new AppError('รหัสเกมไม่ถูกต้อง',400);const rows=await(await must(await db('games?select=id,image_path&id=eq.'+encodeURIComponent(id),{},token),'image.game')).json();if(!rows.length)throw new AppError('ไม่พบเกมนี้',404);return rows[0];}
function objectPath(path:string){return '/storage/v1/object/authenticated/game-images/'+path.split('/').map(encodeURIComponent).join('/');}
export async function GET(req:Request){try{const a=await requireAccess(),g=await game(new URL(req.url).searchParams.get('game')||'',a.token);if(!g.image_path)throw new AppError('ยังไม่มีรูปเกม',404);const r=await must(await supabase(objectPath(g.image_path),{},a.token),'image.read');const bytes=new Uint8Array(await r.arrayBuffer()),type=imageType(bytes);return new Response(bytes,{headers:{'Content-Type':type.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Vary':'Cookie'}});}catch(e){return fail(e);}}
async function remove(path:string,token:string){if(path)await supabase('/storage/v1/object/game-images',{method:'DELETE',body:JSON.stringify({prefixes:[path]})},token);}
export async function POST(req:Request){try{sameOrigin(req);const a=await requireAccess('editor');if(Number(req.headers.get('content-length'))>3*1024*1024+65536)throw new AppError('รูปภาพต้องไม่เกิน 3 MB',413);const f=await req.formData(),id=String(f.get('game')||''),file=f.get('file');const g=await game(id,a.token);if(!(file instanceof File))throw new AppError('กรุณาเลือกรูปภาพ',400);if(file.size>3*1024*1024)throw new AppError('รูปภาพต้องไม่เกิน 3 MB',413);const bytes=new Uint8Array(await file.arrayBuffer()),t=imageType(bytes),path=id+'/'+crypto.randomUUID()+'.'+t.ext;
 await must(await supabase('/storage/v1/object/game-images/'+path,{method:'POST',headers:{'Content-Type':t.mime,'cache-control':'0'},body:bytes},a.token),'image.upload');
 try{const r=await must(await db('games?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({image_path:path})},a.token),'image.save');if(!(await r.json()).length)throw new AppError('เกมถูกลบแล้ว',404);}catch(e){await remove(path,a.token);throw e;}
 await remove(g.image_path,a.token);return reply({ok:true});}catch(e){return fail(e);}}
export async function DELETE(req:Request){try{sameOrigin(req);const a=await requireAccess('editor'),b=await jsonBody(req,1000),g=await game(String(b.game||''),a.token);await must(await db('games?id=eq.'+encodeURIComponent(g.id),{method:'PATCH',body:JSON.stringify({image_path:null})},a.token),'image.remove');await remove(g.image_path,a.token);return reply({ok:true});}catch(e){return fail(e);}}
